### ISSUE TITLE
NameError: name 'temp_dir' is not defined

### ISSUE THREAD

**Issue by koenvervloesem** [Lightslayer/sphinx-docxbuilder#4]
I get this error just by running sphinx-docxbuilder:

```
# Sphinx version: 1.8.4
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   updating environment:
#
#   0 added, 0 changed, 0 removed
#
#   looking for now-outdated files...
#
#   none found
#
#   preparing documents...
#
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from /usr/local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /usr/local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.8.4) from /usr/local/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx-docxbuilder (unknown version) from /usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/__init__.py                                                                                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/builder.py", line 70, in write
    self.prepare_writing(docnames)
  File "/usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/builder.py", line 55, in prepare_writing                                                                                                        
    self.writer = DocxWriter(self)
  File "/usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/writer.py", line 145, in __init__
    self.docx.new_document(stylefile)
  File "/usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/docx/docx.py", line 705, in new_document                                                                                                        
    self.set_style_file(stylefile)
  File "/usr/local/lib/python3.6/site-packages/sphinx-docxbuilder/docx/docx.py", line 652, in set_style_file                                                                                                      
    shutil.rmtree(temp_dir, True)
NameError: name 'temp_dir' is not defined
```

`temp_dir` should probably become `self.template_dir`?

**Comment by koenvervloesem** [comment]
I moved over to [this fork](https://github.com/amedama41/docxbuilder) of the project, that doesn't have this error and is still actively maintained.
